services:
  control:
    build:
      context: .
    tty: true
    working_dir: /lab
    environment:
      ANSIBLE_INVENTORY: /lab/ansible_hosts
    volumes:
      - 'managed:/manage'
      - './lab:/lab'
  manage:
    &manage
    build:
      context: ./node
      dockerfile: Dockerfile
    volumes:
      - managed:/manage
  manage1: *manage
  manage2: *manage
volumes:
  managed: null
